"""empty message

Revision ID: 009c1bb3c0c1
Revises: 604e0e5f8855
Create Date: 2021-05-21 07:01:17.183540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009c1bb3c0c1'
down_revision = '604e0e5f8855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'due_date')
    # ### end Alembic commands ###
