"""empty message

Revision ID: 07b1635575bb
Revises: 580200145a8f
Create Date: 2021-05-18 14:21:00.466886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b1635575bb'
down_revision = '580200145a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_video_join',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'video_id')
    )
    op.add_column('customer', sa.Column('videos_checked_out', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'videos_checked_out')
    op.drop_table('customer_video_join')
    # ### end Alembic commands ###
