"""empty message

Revision ID: 08a104480d01
Revises: c504a3d652e3
Create Date: 2021-05-20 11:52:02.184645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a104480d01'
down_revision = 'c504a3d652e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rental', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rental', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rental', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rental', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
