"""empty message

Revision ID: 0ab26e2b5466
Revises: daddc9aad689
Create Date: 2021-05-19 19:27:38.525504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab26e2b5466'
down_revision = 'daddc9aad689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_column('customers', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('customers', 'customer_id')
    # ### end Alembic commands ###
