"""empty message

Revision ID: 0cefcc6c67b3
Revises: 91554f5e150f
Create Date: 2021-05-18 19:54:41.304460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cefcc6c67b3'
down_revision = '91554f5e150f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_checked_out', sa.Integer(), nullable=True))
    op.drop_column('customers', 'videos_rental')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_rental', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'videos_checked_out')
    # ### end Alembic commands ###
