"""empty message

Revision ID: 0d5d7d0de419
Revises: 8fc1ffe45bd8
Create Date: 2021-05-19 02:42:16.044413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d5d7d0de419'
down_revision = '8fc1ffe45bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('customer', sa.Column('name', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('register_at', sa.DateTime(), nullable=True))
    op.drop_column('customer', 'completed_at')
    op.drop_column('customer', 'customer_id')
    op.drop_column('customer', 'name_of_customer')
    op.add_column('video', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('video', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('video', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('video', 'completed_at')
    op.drop_column('video', 'title_of_video')
    op.drop_column('video', 'video_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('video', sa.Column('title_of_video', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('video', 'title')
    op.drop_column('video', 'release_date')
    op.drop_column('video', 'id')
    op.add_column('customer', sa.Column('name_of_customer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('customer', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'register_at')
    op.drop_column('customer', 'name')
    op.drop_column('customer', 'id')
    # ### end Alembic commands ###
