"""empty message

Revision ID: 100afa38c72d
Revises: 42db2fcbf928
Create Date: 2021-05-21 15:55:58.937361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100afa38c72d'
down_revision = '42db2fcbf928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'postal_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
