"""empty message

Revision ID: 16312039ce48
Revises: 97275c0351e7
Create Date: 2021-05-20 17:47:39.420657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16312039ce48'
down_revision = '97275c0351e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
