"""empty message

Revision ID: 18123dac2b45
Revises: 0da80509439e
Create Date: 2021-05-19 17:31:16.296602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18123dac2b45'
down_revision = '0da80509439e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'total_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'total_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
