"""empty message

Revision ID: 1beca1f3085e
Revises: fa8ba0ad9ca8
Create Date: 2021-11-09 09:01:46.029198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1beca1f3085e'
down_revision = 'fa8ba0ad9ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos_customers', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos_customers', 'id')
    # ### end Alembic commands ###
