"""empty message

Revision ID: 2211b6593382
Revises: fee71ce57462
Create Date: 2021-05-20 14:31:09.631165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2211b6593382'
down_revision = 'fee71ce57462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.alter_column('customer', 'register_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('customer', 'id')
    op.add_column('video', sa.Column('video_id', sa.Integer(), nullable=False))
    op.drop_column('video', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('video', 'video_id')
    op.add_column('customer', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('customer', 'register_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###
