"""empty message

Revision ID: 24acc7acfbac
Revises: 0cedbb66b325
Create Date: 2021-05-21 12:45:51.481906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24acc7acfbac'
down_revision = '0cedbb66b325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'id')
    op.drop_column('video', 'availible_inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('availible_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rental', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
