"""empty message

Revision ID: 2a6fa96d2436
Revises: c4b2206221c4
Create Date: 2021-05-18 16:40:49.186757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6fa96d2436'
down_revision = 'c4b2206221c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'postal_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('postal_code', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
