"""empty message

Revision ID: 2a7cd83fdcf0
Revises: 89cf0e3b9a2d
Create Date: 2021-05-19 10:44:14.787809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7cd83fdcf0'
down_revision = '89cf0e3b9a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('video', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_inventory')
    op.drop_column('rental', 'due_date')
    # ### end Alembic commands ###
