"""empty message

Revision ID: 2db8ba4f4336
Revises: b77bf14a2f5a
Create Date: 2021-05-18 17:42:17.575340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db8ba4f4336'
down_revision = 'b77bf14a2f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_inventory')
    op.drop_column('customer', 'videos_checked_out_count')
    # ### end Alembic commands ###
