"""empty message

Revision ID: 333bb854aaf5
Revises: 93aa27c6b939
Create Date: 2021-05-21 10:34:25.420717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333bb854aaf5'
down_revision = '93aa27c6b939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_inventory')
    # ### end Alembic commands ###
