"""empty message

Revision ID: 42db2fcbf928
Revises: 4b65ae89ed71
Create Date: 2021-05-21 13:43:55.915644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42db2fcbf928'
down_revision = '4b65ae89ed71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental',
    sa.Column('rental_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer', sa.Integer(), nullable=False),
    sa.Column('video', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['video'], ['video.video_id'], ),
    sa.PrimaryKeyConstraint('rental_id', 'customer', 'video')
    )
    op.add_column('video', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_inventory')
    op.drop_table('rental')
    # ### end Alembic commands ###
