"""empty message

Revision ID: 454df4f000b8
Revises: b99b1ba529a7
Create Date: 2021-05-18 11:08:44.693498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454df4f000b8'
down_revision = 'b99b1ba529a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_video_rental',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id', 'customer_id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_video_rental')
    # ### end Alembic commands ###
