"""empty message

Revision ID: 4592a2a6b777
Revises: aeb69410096a
Create Date: 2021-05-20 22:19:27.280274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4592a2a6b777'
down_revision = 'aeb69410096a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rentals', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rentals', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rentals', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rentals', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
