"""empty message

Revision ID: 459b05a250d0
Revises: 44f27c8d4e2e
Create Date: 2021-05-24 20:02:50.800253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459b05a250d0'
down_revision = '44f27c8d4e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.drop_column('customers', 'videos_rented')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_rented', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'videos_checked_out_count')
    # ### end Alembic commands ###
