"""empty message

Revision ID: 475dccb295b8
Revises: 735b88eea498
Create Date: 2021-05-19 22:39:18.194011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475dccb295b8'
down_revision = '735b88eea498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('available_inventory', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('total_inventory', sa.Integer(), nullable=True))
    op.drop_column('video', 'inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('video', 'total_inventory')
    op.drop_column('video', 'available_inventory')
    # ### end Alembic commands ###
