"""empty message

Revision ID: 4ca7f956a5f9
Revises: a809e89364a7
Create Date: 2021-05-21 13:02:41.228464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca7f956a5f9'
down_revision = 'a809e89364a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('rental_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'rental_id')
    # ### end Alembic commands ###
