"""Updates customer columns

Revision ID: 4e8abb2e0f9b
Revises: 5540b408842e
Create Date: 2021-05-17 11:33:59.806836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e8abb2e0f9b'
down_revision = '5540b408842e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.drop_column('customer', 'phone_number')
    op.drop_column('customer', 'register_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('register_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'registered_at')
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
