"""empty message

Revision ID: 524863d721b5
Revises: e699e09cabc8
Create Date: 2021-05-18 14:57:29.301597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524863d721b5'
down_revision = 'e699e09cabc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_inventory')
    # ### end Alembic commands ###
