"""empty message

Revision ID: 53027026e081
Revises: 100afa38c72d
Create Date: 2021-05-21 15:57:15.402906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53027026e081'
down_revision = '100afa38c72d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('postal_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'postal_code')
    # ### end Alembic commands ###
