"""empty message

Revision ID: 54de02d4de2b
Revises: 96ea35adf211
Create Date: 2021-05-19 20:27:29.417651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54de02d4de2b'
down_revision = '96ea35adf211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('available_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
