"""changed customer column

Revision ID: 553ef26ddd3c
Revises: 6e1721f8e03b
Create Date: 2021-05-18 11:04:10.460095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553ef26ddd3c'
down_revision = '6e1721f8e03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.drop_column('customers', 'videos_checked_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_checked_out', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'videos_checked_out_count')
    # ### end Alembic commands ###
