"""empty message

Revision ID: 567ac73cc1e1
Revises: 1e5ca2d6624d
Create Date: 2021-05-21 10:40:13.371138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567ac73cc1e1'
down_revision = '1e5ca2d6624d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_inventory')
    # ### end Alembic commands ###
