"""empty message

Revision ID: 568f9f5d13c6
Revises: 36a1538ed48e
Create Date: 2021-05-20 14:01:39.293651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568f9f5d13c6'
down_revision = '36a1538ed48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'id')
    # ### end Alembic commands ###
