"""empty message

Revision ID: 580200145a8f
Revises: 51c6c85de9ce
Create Date: 2021-05-18 11:30:13.162152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580200145a8f'
down_revision = '51c6c85de9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('total_inventory', sa.Integer(), nullable=True))
    op.drop_column('video', 'inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('video', 'total_inventory')
    # ### end Alembic commands ###
