"""empty message

Revision ID: 596de2448ebf
Revises: 1691f0673fc5
Create Date: 2021-05-18 15:51:35.800330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596de2448ebf'
down_revision = '1691f0673fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('customer', 'id')
    # ### end Alembic commands ###
