"""empty message

Revision ID: 5cbe6efd23d2
Revises: cf53c8d98630
Create Date: 2021-05-17 15:06:31.428680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbe6efd23d2'
down_revision = 'cf53c8d98630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('postal_code', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('register_at', sa.DateTime(), nullable=False))
    op.add_column('video', sa.Column('release_date', sa.DateTime(), nullable=False))
    op.add_column('video', sa.Column('total_inventory', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'total_inventory')
    op.drop_column('video', 'release_date')
    op.drop_column('customer', 'register_at')
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###
