"""empty message

Revision ID: 5df3ded41338
Revises: 3d0703e3fb56
Create Date: 2021-11-08 21:51:01.978812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df3ded41338'
down_revision = '3d0703e3fb56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos_customers', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos_customers', 'id')
    # ### end Alembic commands ###
