"""empty message

Revision ID: 604e0e5f8855
Revises: 475dccb295b8
Create Date: 2021-05-20 11:31:49.769097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604e0e5f8855'
down_revision = '475dccb295b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.video_id'], ),
    sa.PrimaryKeyConstraint('id', 'customer_id', 'video_id')
    )
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'videos_checked_out_count')
    op.drop_table('rental')
    # ### end Alembic commands ###
