"""empty message

Revision ID: 604f5a237adf
Revises: 962d5c31e9ab
Create Date: 2021-05-19 11:49:17.543539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604f5a237adf'
down_revision = '962d5c31e9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('due_date', sa.Date(), nullable=True))
    op.drop_constraint('video_customer_id_fkey', 'video', type_='foreignkey')
    op.drop_column('video', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('video_customer_id_fkey', 'video', 'customer', ['customer_id'], ['id'])
    op.drop_column('rental', 'due_date')
    # ### end Alembic commands ###
