"""empty message

Revision ID: 64bcb016ab2a
Revises: 8dfcf63e5d9d
Create Date: 2021-05-20 12:18:19.690891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64bcb016ab2a'
down_revision = '8dfcf63e5d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('video', sa.Column('video_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('video', 'id')
    op.drop_column('video', 'released_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('released_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('video', 'video_id')
    op.drop_column('video', 'release_date')
    # ### end Alembic commands ###
