"""empty message

Revision ID: 66266a04ee5f
Revises: d64bad11b3b8
Create Date: 2021-05-18 12:26:49.308963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66266a04ee5f'
down_revision = 'd64bad11b3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###
