"""empty message

Revision ID: 6bd066dbf8cb
Revises: b4087acb14d1
Create Date: 2021-05-20 17:19:51.458782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bd066dbf8cb'
down_revision = 'b4087acb14d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.drop_constraint('customer_video_id_fkey', 'customer', type_='foreignkey')
    op.drop_column('customer', 'video_id')
    op.drop_column('customer', 'register_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('register_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('customer_video_id_fkey', 'customer', 'video', ['video_id'], ['video_id'])
    op.drop_column('customer', 'registered_at')
    # ### end Alembic commands ###
