"""empty message

Revision ID: 6e1721f8e03b
Revises: 15c67af3e5ae
Create Date: 2021-05-17 18:39:26.594428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1721f8e03b'
down_revision = '15c67af3e5ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_checked_out', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'available_inventory')
    op.drop_column('customers', 'videos_checked_out')
    # ### end Alembic commands ###
