"""empty message

Revision ID: 7095c6cdb999
Revises: 524863d721b5
Create Date: 2021-05-18 22:48:57.435508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7095c6cdb999'
down_revision = '524863d721b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('rental', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('rental', sa.Column('video_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['id'])
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_column('rental', 'video_id')
    op.drop_column('rental', 'due_date')
    op.drop_column('rental', 'customer_id')
    # ### end Alembic commands ###
