"""empty message

Revision ID: 735b88eea498
Revises: 9670fe262169
Create Date: 2021-05-19 21:10:45.887973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735b88eea498'
down_revision = '9670fe262169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('postal_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'postal_code')
    # ### end Alembic commands ###
