"""empty message

Revision ID: 79771c128f9c
Revises: 0bfeedf1511d
Create Date: 2021-05-19 21:12:08.949371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79771c128f9c'
down_revision = '0bfeedf1511d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.video_id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'video_id')
    )
    op.drop_table('checked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checked',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='checked_customer_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['video.video_id'], name='checked_video_id_fkey'),
    sa.PrimaryKeyConstraint('customer_id', 'video_id', name='checked_pkey')
    )
    op.drop_table('rental')
    # ### end Alembic commands ###
