"""empty message

Revision ID: 7c4c3ed70f15
Revises: b457e6784a2f
Create Date: 2021-05-21 15:58:09.233290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4c3ed70f15'
down_revision = 'b457e6784a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_name_key', 'customers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('customers_name_key', 'customers', ['name'])
    # ### end Alembic commands ###
