"""empty message

Revision ID: 8537e2d6eab1
Revises: 700b1819e2c9
Create Date: 2021-05-21 14:25:48.183500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8537e2d6eab1'
down_revision = '700b1819e2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('available_inventory', sa.Integer(), nullable=True))
    op.drop_column('videos', 'avail_inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('avail_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('videos', 'available_inventory')
    op.drop_column('customers', 'videos_checked_out_count')
    # ### end Alembic commands ###
