"""empty message

Revision ID: 855ad2c04789
Revises: 87de61a1e999
Create Date: 2021-05-20 16:06:18.975309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855ad2c04789'
down_revision = '87de61a1e999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='rentals_customer_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['video.video_id'], name='rentals_video_id_fkey'),
    sa.PrimaryKeyConstraint('customer_id', 'video_id', name='rentals_pkey')
    )
    # ### end Alembic commands ###
