"""empty message

Revision ID: 85653691b7ad
Revises: d8a7d33861c9
Create Date: 2021-05-19 00:03:08.560295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85653691b7ad'
down_revision = 'd8a7d33861c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_inventory')
    # ### end Alembic commands ###
