"""empty message

Revision ID: 8d15ecc642cd
Revises: 53e962f980e0
Create Date: 2021-05-21 16:23:39.117121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d15ecc642cd'
down_revision = '53e962f980e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.drop_column('videos', 'release_date_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('release_date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('videos', 'release_date')
    # ### end Alembic commands ###
