"""empty message

Revision ID: 8fc1ffe45bd8
Revises: b5024c7ced22
Create Date: 2021-05-18 13:03:06.717397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc1ffe45bd8'
down_revision = 'b5024c7ced22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('customer', sa.Column('name_of_customer', sa.String(), nullable=True))
    op.drop_column('customer', 'name')
    op.add_column('video', sa.Column('title_of_video', sa.String(), nullable=True))
    op.add_column('video', sa.Column('video_id', sa.Integer(), nullable=False))
    op.drop_column('video', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('video', 'video_id')
    op.drop_column('video', 'title_of_video')
    op.add_column('customer', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('customer', 'name_of_customer')
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###
