"""empty message

Revision ID: 921220722cf0
Revises: a0602f2df0c8
Create Date: 2021-05-18 13:41:14.913264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921220722cf0'
down_revision = 'a0602f2df0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('left', sa.Column('videos_checked_out', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('left', 'videos_checked_out')
    # ### end Alembic commands ###
