"""empty message

Revision ID: 948144d20bb0
Revises: 96151a9a510a
Create Date: 2021-05-18 17:18:06.648326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948144d20bb0'
down_revision = '96151a9a510a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.drop_column('customer', 'videos_checked_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'videos_checked_out_count')
    # ### end Alembic commands ###
