"""empty message

Revision ID: 962d5c31e9ab
Revises: b00dcc6ba758
Create Date: 2021-05-19 10:51:20.387043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962d5c31e9ab'
down_revision = 'b00dcc6ba758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'video', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_column('video', 'customer_id')
    # ### end Alembic commands ###
