"""empty message

Revision ID: 9670fe262169
Revises: 66266a04ee5f
Create Date: 2021-05-19 21:10:02.074616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9670fe262169'
down_revision = '66266a04ee5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'postal_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('postal_code', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
