"""empty message

Revision ID: 97eb09f078b5
Revises: 07b1635575bb
Create Date: 2021-05-18 14:28:54.703733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97eb09f078b5'
down_revision = '07b1635575bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.drop_column('customer', 'videos_checked_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'videos_checked_out_count')
    # ### end Alembic commands ###
