"""empty message

Revision ID: 9886541a5352
Revises: 15c6297991df
Create Date: 2021-05-21 14:45:44.522130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9886541a5352'
down_revision = '15c6297991df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'videos_checked_out_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'videos_checked_out_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
