"""empty message

Revision ID: 98add18b5a90
Revises: 7a6ce2e556a6
Create Date: 2021-05-18 11:20:24.705694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98add18b5a90'
down_revision = '7a6ce2e556a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'videos_checked_out')
    # ### end Alembic commands ###
