"""empty message

Revision ID: 98b5df108a02
Revises: e84048696c3d
Create Date: 2021-05-21 13:17:02.623898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b5df108a02'
down_revision = 'e84048696c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'rental_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('rental_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
