"""empty message

Revision ID: 996cbd82d267
Revises: 98add18b5a90
Create Date: 2021-05-18 11:53:08.439823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996cbd82d267'
down_revision = '98add18b5a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.drop_column('customer', 'videos_checked_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'videos_checked_out_count')
    # ### end Alembic commands ###
