"""empty message

Revision ID: 9e4dd674450e
Revises: 7515e7b242f4
Create Date: 2021-05-18 15:55:46.759544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4dd674450e'
down_revision = '7515e7b242f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'videos_checked_out')
    # ### end Alembic commands ###
