"""empty message

Revision ID: a48766184924
Revises: e6988aa123f4
Create Date: 2021-05-21 14:58:05.667730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48766184924'
down_revision = 'e6988aa123f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'total_inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('total_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
