"""empty message

Revision ID: a522a33734b6
Revises: 21e59676e268
Create Date: 2021-05-20 11:30:01.820962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a522a33734b6'
down_revision = '21e59676e268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'videos_checked_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_checked_out', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
