"""empty message

Revision ID: a7245725c9af
Revises: 7095c6cdb999
Create Date: 2021-05-19 22:20:44.215710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7245725c9af'
down_revision = '7095c6cdb999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('check_in_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'check_in_date')
    # ### end Alembic commands ###
