"""empty message

Revision ID: a74af78225dd
Revises: 63a856150660
Create Date: 2021-05-19 10:14:13.948058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74af78225dd'
down_revision = '63a856150660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
