"""empty message

Revision ID: ad4024d03da4
Revises: f1a4265171c5
Create Date: 2021-05-22 12:19:03.382679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4024d03da4'
down_revision = 'f1a4265171c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'status')
    # ### end Alembic commands ###
