"""empty message

Revision ID: b00dcc6ba758
Revises: 2a6fa96d2436
Create Date: 2021-05-18 16:41:42.290162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00dcc6ba758'
down_revision = '2a6fa96d2436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('postal_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'postal_code')
    # ### end Alembic commands ###
