"""empty message

Revision ID: b457e6784a2f
Revises: 8537e2d6eab1
Create Date: 2021-05-21 14:30:01.483395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b457e6784a2f'
down_revision = '8537e2d6eab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(), nullable=False))
    op.drop_column('customers', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
