"""empty message

Revision ID: b4c619ceed86
Revises: ce456522578f
Create Date: 2021-05-19 00:03:15.246628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4c619ceed86'
down_revision = 'ce456522578f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.drop_column('customer', 'phone_num')
    op.drop_column('customer', 'register_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('register_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('phone_num', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'registered_at')
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
