"""empty message

Revision ID: b9e3fc601794
Revises: f1de1df816a3
Create Date: 2021-05-20 17:24:49.431391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e3fc601794'
down_revision = 'f1de1df816a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_video_rental', sa.Column('outstanding', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_video_rental', 'outstanding')
    # ### end Alembic commands ###
