"""empty message

Revision ID: bd4d3310057f
Revises: 0cefcc6c67b3
Create Date: 2021-05-18 20:12:28.133549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4d3310057f'
down_revision = '0cefcc6c67b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.drop_column('customers', 'videos_checked_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_checked_out', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'videos_checked_out_count')
    # ### end Alembic commands ###
