"""empty message

Revision ID: bd62f7b6b40c
Revises: ad1c1130f4ee
Create Date: 2021-05-20 15:28:37.424468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd62f7b6b40c'
down_revision = 'ad1c1130f4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.drop_column('customers', 'register_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('register_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'registered_at')
    # ### end Alembic commands ###
