"""empty message

Revision ID: c022aaaa05af
Revises: abb033bec16f
Create Date: 2021-05-18 20:40:18.101487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c022aaaa05af'
down_revision = 'abb033bec16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('total_inventory', sa.Integer(), nullable=True))
    op.drop_column('video', 'inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('video', 'total_inventory')
    # ### end Alembic commands ###
