"""empty message

Revision ID: c34cdad0fd91
Revises: b192a7db7b2d
Create Date: 2021-05-18 11:39:07.948764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c34cdad0fd91'
down_revision = 'b192a7db7b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.String(), nullable=True))
    op.drop_column('video', 'register_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('register_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'videos_checked_out_count')
    # ### end Alembic commands ###
