"""empty message

Revision ID: c4b2206221c4
Revises: 1a4517ac1291
Create Date: 2021-05-18 15:39:21.097540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b2206221c4'
down_revision = '1a4517ac1291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id', 'customer_id', 'video_id')
    )
    op.drop_table('customer_video_join')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_video_join',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='customer_video_join_customer_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name='customer_video_join_video_id_fkey'),
    sa.PrimaryKeyConstraint('customer_id', 'video_id', name='customer_video_join_pkey')
    )
    op.drop_table('rental')
    # ### end Alembic commands ###
