"""empty message

Revision ID: c60b23fe6923
Revises: 0038e3e06106
Create Date: 2021-05-18 14:17:01.602006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60b23fe6923'
down_revision = '0038e3e06106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('customer', 'id')
    # ### end Alembic commands ###
