"""empty message

Revision ID: c776035fa577
Revises: c60b23fe6923
Create Date: 2021-05-18 14:27:40.410302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c776035fa577'
down_revision = 'c60b23fe6923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('video', 'video_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('video', 'id')
    # ### end Alembic commands ###
