"""empty message

Revision ID: cd1cdf36dcf8
Revises: 4231dcf764f4
Create Date: 2021-05-18 20:42:04.608615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1cdf36dcf8'
down_revision = '4231dcf764f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'title')
    # ### end Alembic commands ###
