"""empty message

Revision ID: ce089575dc0c
Revises: 3f5bd27a384b
Create Date: 2021-05-19 20:55:48.804057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce089575dc0c'
down_revision = '3f5bd27a384b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.drop_column('customer', 'register_at')
    op.drop_column('customer', 'phone_number')
    op.alter_column('video', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('video', 'total_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'total_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('video', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('register_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'videos_checked_out_count')
    op.drop_column('customer', 'registered_at')
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
