"""empty message

Revision ID: ce456522578f
Revises: 7c4dd2892132
Create Date: 2021-05-18 23:25:48.959805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce456522578f'
down_revision = '7c4dd2892132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'phone_num')
    # ### end Alembic commands ###
