"""empty message

Revision ID: d244f6a24312
Revises: 0b9b34264baa
Create Date: 2021-05-19 19:19:54.330823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd244f6a24312'
down_revision = '0b9b34264baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('customers', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
