"""adds checkout date to rental model

Revision ID: d3ee1b567ee7
Revises: bd3cb8094bc2
Create Date: 2021-05-21 16:01:45.399809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ee1b567ee7'
down_revision = 'bd3cb8094bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('checkout_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'checkout_date')
    # ### end Alembic commands ###
