"""empty message

Revision ID: d48e306f4884
Revises: 59c7fc1b0244
Create Date: 2021-05-21 16:53:01.636183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48e306f4884'
down_revision = '59c7fc1b0244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'phone')
    # ### end Alembic commands ###
