"""empty message

Revision ID: d64bad11b3b8
Revises: 04b23fdb0f1c
Create Date: 2021-05-18 12:26:02.647855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64bad11b3b8'
down_revision = '04b23fdb0f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
