"""empty message

Revision ID: d8b8db80d4aa
Revises: a7dfee0230ad
Create Date: 2021-05-20 16:10:06.127184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b8db80d4aa'
down_revision = 'a7dfee0230ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'total_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'total_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
