"""empty message

Revision ID: d9f9074cb017
Revises: 553ef26ddd3c
Create Date: 2021-05-18 11:16:10.194576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9f9074cb017'
down_revision = '553ef26ddd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.drop_column('customers', 'register_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('register_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'registered_at')
    # ### end Alembic commands ###
