"""empty message

Revision ID: daddc9aad689
Revises: 0b6f4337573c
Create Date: 2021-05-19 12:06:02.656322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daddc9aad689'
down_revision = '0b6f4337573c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'available_inventory')
    op.drop_column('customers', 'videos_checked_out_count')
    # ### end Alembic commands ###
