"""empty message

Revision ID: e733b103d2bc
Revises: 921220722cf0
Create Date: 2021-05-18 20:14:32.668298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e733b103d2bc'
down_revision = '921220722cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('right', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('right', 'available_inventory')
    # ### end Alembic commands ###
