"""Updated Video model

Revision ID: ed8b25f5f118
Revises: e0daef14b5c6
Create Date: 2021-05-20 18:50:53.660708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8b25f5f118'
down_revision = 'e0daef14b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('total_inventory', sa.Integer(), nullable=True))
    op.drop_column('videos', 'inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('videos', 'total_inventory')
    # ### end Alembic commands ###
