"""empty message

Revision ID: f72326914d97
Revises: c1f217fa16fc
Create Date: 2021-05-21 17:34:24.484611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72326914d97'
down_revision = 'c1f217fa16fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
