"""empty message

Revision ID: f728305ae08c
Revises: 2d98dd6cbb61
Create Date: 2021-05-17 12:33:30.551346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f728305ae08c'
down_revision = '2d98dd6cbb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('registered_at', sa.String(), nullable=True))
    op.drop_column('customer', 'register_at')
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('register_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'registered_at')
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
