"""empty message

Revision ID: f85ce26c038a
Revises: a73be3d7b5c9
Create Date: 2021-05-18 20:25:25.914478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85ce26c038a'
down_revision = 'a73be3d7b5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'videos_checked_out')
    # ### end Alembic commands ###
