"""empty message

Revision ID: fa8ba0ad9ca8
Revises: 5df3ded41338
Create Date: 2021-11-09 07:18:00.112213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8ba0ad9ca8'
down_revision = '5df3ded41338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'postal_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('videos_customers', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos_customers', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('customer', 'postal_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
