"""empty message

Revision ID: fe31433ac12e
Revises: eac85e1e3fad
Create Date: 2021-05-17 20:46:27.761543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe31433ac12e'
down_revision = 'eac85e1e3fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('registered_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'registered_at')
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###
