"""empty message

Revision ID: fee71ce57462
Revises: ca6d349c45a2
Create Date: 2021-05-20 10:11:52.755942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee71ce57462'
down_revision = 'ca6d349c45a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=False))
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
